name: cds
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.7
  - anaconda
  - jupyterlab=1.1.4
  - scikit-learn=0.21
  - spacy=2.2
  - gensim
  - pyldavis
  - wordcloud
  - python-snappy
  - fastparquet
  - inflect
  - keras
  - pip
  - graphviz
  - pip:
    - scikit-multilearn
    - contractions
    - streamlit
    - graphviz
